architecture: arm
board_socs:
- name: stm32f407xx
defconfig_file: boards/segger/trb_stm32f407/segger_trb_stm32f407_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SEGGER_TRB_STM32F407
vendor: segger
