architecture: arm
board_socs:
- name: nrf54l15
  variants:
  - cpucluster: cpuflpr
    name: xip
defconfig_file: boards/nordic/nrf54l15pdk/nrf54l15pdk_nrf54l15_cpuapp_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NRF54L15PDK_NRF54L15_CPUAPP
vendor: nordic
