architecture: arm
board_socs:
- name: same70q21
- name: same70q21b
defconfig_file: boards/atmel/sam/sam_e70_xplained/sam_e70_xplained_same70q21_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SAM_E70_XPLAINED_SAME70Q21
vendor: atmel
