architecture: arm
board_socs:
- name: efr32mg12p432f1024gl125
defconfig_file: boards/silabs/radio_boards/slwrb4161a/slwrb4161a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLWRB4161A
vendor: unknown
