architecture: arm
board_socs:
- name: nrf9160
  variants:
  - name: ns
defconfig_file: boards/actinius/icarus/actinius_icarus_nrf9160_ns_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ACTINIUS_ICARUS_1_4_0_NRF9160
vendor: actinius
