architecture: arm
board_socs:
- name: designstart_fpga_cortex_m3
defconfig_file: boards/sc/scobc_module1/scobc_module1_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SCOBC_MODULE1
vendor: spacecubics
