architecture: arm
board_socs:
- name: efr32fg1p133f256gm48
defconfig_file: boards/silabs/radio_boards/slwrb4250b/slwrb4250b_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLWRB4250B
vendor: unknown
