architecture: arm
board_socs:
- name: msp432p401r
defconfig_file: boards/ti/msp_exp432p401r_launchxl/msp_exp432p401r_launchxl_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MSP_EXP432P401R_LAUNCHXL
vendor: ti
