architecture: arm
board_socs:
- name: efr32mg24b020f1536im40
defconfig_file: boards/sparkfun/thing_plus_matter_mgm240p/sparkfun_thing_plus_matter_mgm240p_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SPARKFUN_THING_PLUS_MATTER_MGM240P
vendor: sparkfun
