architecture: arm
board_socs:
- name: lpc55s69
  variants:
  - cpucluster: cpu0
    name: ns
defconfig_file: boards/nxp/lpcxpresso55s69/lpcxpresso55s69_lpc55s69_cpu0_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_LPCXPRESSO55S69_LPC55S69_CPU0
vendor: nxp
