add_defconfig_flags:
- CONFIG_CMU_HFXO_FREQ=38400000
- CONFIG_CMU_LFXO_FREQ=32768
architecture: arm
board_name: efr32bg22_brd4184a
board_socs:
- name: efr32bg22c224f512im40
defconfig_file: boards/silabs/dev_kits/sltb010a/sltb010a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLTB010A_0
select:
- SOC_PART_NUMBER_EFR32BG22C224F512IM40
vendor: silabs
