architecture: xtensa
board_socs:
- name: mimx8qx6
defconfig_file: boards/nxp/imx8qxp_mek/imx8qxp_mek_mimx8qx6_adsp_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_IMX8QXP_MEK_MIMX8QX6_ADSP
vendor: nxp
