architecture: xtensa
board_socs:
- name: cavs25
  variants:
  - name: tgph
- name: ace15_mtpm
- name: ace20_lnl
defconfig_file: boards/intel/adsp/intel_adsp_cavs25_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_INTEL_ADSP_CAVS25
vendor: intel
