architecture: arm
board_socs:
- name: cy8c624abzi_s2d44
defconfig_file: boards/cypress/cy8cproto_062_4343w/cy8cproto_062_4343w_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_CY8CPROTO_062_4343W
vendor: cypress
