architecture: arm
board_socs:
- name: mimxrt1189
defconfig_file: boards/nxp/mimxrt1180_evk/mimxrt1180_evk_mimxrt1189_cm33_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MIMXRT1180_EVK_MIMXRT1189_CM33
vendor: nxp
