architecture: arm
board_socs:
- name: efr32mg24b220f1536im48
defconfig_file: boards/silabs/radio_boards/xg24_rb4187c/xg24_rb4187c_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_XG24_RB4187C
vendor: unknown
