architecture: arm
board_socs:
- name: mimxrt595s
defconfig_file: boards/nxp/mimxrt595_evk/mimxrt595_evk_mimxrt595s_cm33_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MIMXRT595_EVK_MIMXRT595S_CM33
vendor: nxp
