architecture: arm
board_socs:
- name: efr32mg21a020f1024im32
defconfig_file: boards/silabs/radio_boards/slwrb4180a/slwrb4180a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLWRB4180A
vendor: unknown
