architecture: arm
board_socs:
- name: an385
- name: an521
  variants:
  - cpucluster: cpu0
    name: ns
defconfig_file: boards/arm/mps2/mps2_an385_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MPS2_AN385
vendor: arm
