architecture: riscv
board_socs:
- name: sy120_gbm
- name: sy120_gen1
defconfig_file: boards/sensry/ganymed_bob/ganymed_bob_sy120_gbm_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_GANYMED_BOB_SY120_GBM
vendor: sensry
