architecture: arm
board_socs:
- name: stm32l475xx
defconfig_file: boards/alientek/pandora_stm32l475/pandora_stm32l475_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_PANDORA_STM32L475
vendor: alientek
