architecture: arm
board_socs:
- name: samd21g18a
defconfig_file: boards/adafruit/feather_m0_basic_proto/adafruit_feather_m0_basic_proto_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ADAFRUIT_FEATHER_M0_BASIC_PROTO
vendor: adafruit
