architecture: arm
board_socs:
- name: nrf52840
defconfig_file: boards/adafruit/feather_nrf52840/adafruit_feather_nrf52840_express_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ADAFRUIT_FEATHER_NRF52840_EXPRESS
vendor: adafruit
