architecture: arm
board_socs:
- name: nrf52840
defconfig_file: boards/adafruit/feather/adafruit_feather_nrf52840_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ADAFRUIT_FEATHER_NRF52840
vendor: adafruit
