architecture: arm
board_socs:
- name: mimx8ml8
  variants:
  - cpucluster: a53
    name: smp
  - cpucluster: m7
    name: ddr
defconfig_file: boards/nxp/imx8mp_evk/imx8mp_evk_mimx8ml8_m7_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_IMX8MP_EVK_MIMX8ML8_M7
vendor: nxp
