architecture: arm
board_socs:
- name: am6234
defconfig_file: boards/phytec/phyboard_lyra_am62x/phyboard_lyra_am62x_am6234_m4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_PHYBOARD_LYRA_AM62X_AM6234_M4
vendor: phytec
