architecture: arm
board_socs:
- name: mimxrt1166
defconfig_file: boards/nxp/mimxrt1160_evk/mimxrt1160_evk_mimxrt1166_cm4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MIMXRT1160_EVK_MIMXRT1166_CM4
vendor: nxp
