architecture: arm
board_socs:
- name: samd51p20a
defconfig_file: boards/adafruit/grand_central_m4_express/adafruit_grand_central_m4_express_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ADAFRUIT_GRAND_CENTRAL_M4_EXPRESS
vendor: adafruit
