architecture: arm
board_socs:
- name: stm32l552xx
  variants:
  - name: ns
defconfig_file: boards/st/nucleo_l552ze_q/nucleo_l552ze_q_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NUCLEO_L552ZE_Q
vendor: st
