architecture: arm
board_socs:
- name: mec1501_hsz
defconfig_file: boards/microchip/mec1501modular_assy6885/mec1501modular_assy6885_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MEC1501MODULAR_ASSY6885
vendor: microchip
