architecture: riscv
board_socs:
- name: openisa_rv32m1
defconfig_file: boards/openisa/rv32m1_vega/rv32m1_vega_openisa_rv32m1_ri5cy_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_RV32M1_VEGA_OPENISA_RV32M1_RI5CY
vendor: openisa
