architecture: arm
board_socs:
- name: stm32l552xx
  variants:
  - name: ns
defconfig_file: boards/st/nucleo_l552ze_q/nucleo_l552ze_q_stm32l552xx_ns_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NUCLEO_L552ZE_Q_STM32L552XX_NS
vendor: st
