architecture: arm
board_socs:
- name: efr32mg12p332f1024gl125
defconfig_file: boards/silabs/efr32mg_sltb004a/efr32mg_sltb004a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFR32MG_SLTB004A
vendor: silabs
