architecture: riscv
board_socs:
- name: efinix_sapphire
defconfig_file: boards/efinix/titanium_ti60_f225/titanium_ti60_f225_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_TITANIUM_TI60_F225
vendor: efinix
