architecture: riscv
board_socs:
- name: opentitan
defconfig_file: boards/lowrisc/opentitan_earlgrey/opentitan_earlgrey_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_OPENTITAN_EARLGREY
vendor: lowrisc
