architecture: arm
board_socs:
- name: stm32wle5xx
defconfig_file: boards/olimex/lora_stm32wl_devkit/olimex_lora_stm32wl_devkit_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_OLIMEX_LORA_STM32WL_DEVKIT
vendor: olimex
