architecture: xtensa
board_socs:
- name: esp32s3
defconfig_file: boards/seeed/xiao_esp32s3/xiao_esp32s3_esp32s3_procpu_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_XIAO_ESP32S3_ESP32S3_PROCPU
vendor: seeed
