architecture: arm
board_socs:
- name: efr32fg13p233f512gm48
defconfig_file: boards/silabs/radio_boards/slwrb4255a/slwrb4255a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLWRB4255A
vendor: unknown
