architecture: arc
board_socs:
- name: emsk_em7d
- name: emsk_em9d
- name: emsk_em11d
defconfig_file: boards/snps/em_starterkit/em_starterkit_emsk_em11d_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EM_STARTERKIT_EMSK_EM11D
vendor: snps
