architecture: xtensa
board_socs:
- name: esp32
defconfig_file: boards/m5stack/m5stack_atom_lite/m5stack_atom_lite_procpu_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_M5STACK_ATOM_LITE_ESP32_PROCPU
vendor: m5stack
