architecture: arm
board_socs:
- name: mimxrt1176
defconfig_file: boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm7_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MIMXRT1170_EVK_B_MIMXRT1176_CM7
vendor: nxp
