architecture: arm
board_socs:
- name: samd51g19a
defconfig_file: boards/adafruit/itsybitsy_m4_express/adafruit_itsybitsy_m4_express_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ADAFRUIT_ITSYBITSY_M4_EXPRESS
vendor: adafruit
