architecture: arm
board_socs:
- name: stm32h755xx
defconfig_file: boards/st/nucleo_h755zi_q/nucleo_h755zi_q_stm32h755xx_m4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NUCLEO_H755ZI_Q_STM32H755XX_M4
vendor: st
