architecture: arm
board_socs:
- name: stm32f446xx
defconfig_file: boards/96boards/stm32_sensor_mez/96b_stm32_sensor_mez_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_96B_STM32_SENSOR_MEZ
vendor: st
