architecture: arm
board_socs:
- name: mec172x_nsz
defconfig_file: boards/microchip/mec172xevb_assy6906/mec172xevb_assy6906_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MEC172XEVB_ASSY6906
vendor: microchip
