architecture: xtensa
board_socs:
- name: cavs25
  variants:
  - name: tgph
- name: ace15_mtpm
- name: ace20_lnl
- name: ace30_ptl
defconfig_file: boards/intel/adsp/intel_adsp_ace30_ptl_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_INTEL_ADSP_ACE30_PTL
vendor: intel
