architecture: arm
board_socs:
- name: musca_s1
  variants:
  - name: ns
defconfig_file: boards/arm/v2m_musca_s1/v2m_musca_s1_musca_s1_ns_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_V2M_MUSCA_S1_MUSCA_S1
vendor: arm
