architecture: arm
board_socs:
- name: stm32f405xx
defconfig_file: boards/adafruit/feather_stm32f405/adafruit_feather_stm32f405_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ADAFRUIT_FEATHER_STM32F405
vendor: adafruit
