architecture: arm
board_socs:
- name: am6442
defconfig_file: boards/phytec/phyboard_electra/phyboard_electra_am6442_m4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_PHYBOARD_ELECTRA_AM6442_M4
vendor: phytec
