architecture: arm
board_socs:
- name: efr32bg13p632f512gm48
defconfig_file: boards/silabs/radio_boards/slwrb4104a/slwrb4104a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLWRB4104A
vendor: unknown
