architecture: arm
board_socs:
- name: efr32mg24b310f1536im48
defconfig_file: boards/silabs/efr32xg24_dk2601b/efr32xg24_dk2601b_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFR32XG24_DK2601B
vendor: silabs
