architecture: arm
board_socs:
- name: cc1352p7
defconfig_file: boards/beagle/beagleconnect_freedom/beagleconnect_freedom_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_BEAGLECONNECT_FREEDOM
vendor: beagle
