architecture: arm
board_socs:
- name: r7fa4m1ab3cfm
defconfig_file: boards/arduino/uno_r4_minima/arduino_uno_r4_minima_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ARDUINO_UNO_R4_MINIMA
vendor: arduino
