architecture: arm
board_socs:
- name: nrf9151
  variants:
  - name: ns
defconfig_file: boards/nordic/nrf9151dk/nrf9151dk_nrf9151_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NRF9151DK_NRF9151
vendor: nordic
