architecture: arm
board_socs:
- name: stm32h747xx
defconfig_file: boards/arduino/giga_r1/arduino_giga_r1_stm32h747xx_m4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ARDUINO_GIGA_R1_STM32H747XX_M4
vendor: arduino
