architecture: riscv
defconfig_file: boards/riscv/mpfs_icicle/mpfs_icicle_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MPFS_ICICLE
select:
- 64BIT
- SCHED_IPI_SUPPORTED
- CPU_HAS_FPU_DOUBLE_PRECISION
