architecture: arm64
board_socs:
- name: am6234
defconfig_file: boards/phytec/phycore_am62x/phycore_am62x_am6234_a53_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_PHYCORE_AM62X_AM6234_A53
vendor: phytec
