architecture: arm
board_socs:
- name: designstart_fpga_cortex_m1
- name: designstart_fpga_cortex_m3
defconfig_file: boards/digilent/arty_a7/arty_a7_designstart_fpga_cortex_m1_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ARTY_A7_DESIGNSTART_FPGA_CORTEX_M1
vendor: digilent
