architecture: arm64
board_socs:
- name: r8a77951
defconfig_file: boards/renesas/rcar_h3ulcb/rcar_h3ulcb_r8a77951_a57_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_RCAR_H3ULCB_R8A77951_A57
vendor: renesas
