architecture: x86
board_socs:
- name: elkhart_lake
  variants:
  - name: sbl
defconfig_file: boards/intel/ehl/intel_ehl_crb_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_INTEL_EHL_CRB
vendor: intel
