architecture: arm
board_socs:
- name: nrf52840
- name: nrf52811
defconfig_file: boards/nordic/nrf52840dk/nrf52840dk_nrf52811_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NRF52840DK_NRF52811
vendor: nordic
