add_defconfig_flags:
- CONFIG_SOC_SERIES_EFR32BG22=y
- CONFIG_CMU_HFXO_FREQ=38400000
- CONFIG_CMU_LFXO_FREQ=32768
architecture: arm
board_name: efr32bg22_brd4184a
defconfig_file: boards/arm/efr32_thunderboard/efr32bg22_brd4184a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFR32BG22_BRD4184A
select:
- SOC_PART_NUMBER_EFR32BG22C224F512IM40
