architecture: xtensa
board_socs:
- name: esp32s2
defconfig_file: boards/franzininho/esp32s2_franzininho/esp32s2_franzininho_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ESP32S2_FRANZININHO
vendor: espressif
