architecture: arm
board_socs:
- name: mcxn947
  variants:
  - cpucluster: cpu0
    name: qspi
defconfig_file: boards/nxp/frdm_mcxn947/frdm_mcxn947_mcxn947_cpu0_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_FRDM_MCXN947_MCXN947_CPU0
vendor: nxp
