architecture: arm
board_socs:
- name: stm32h745xx
defconfig_file: boards/st/nucleo_h745zi_q/nucleo_h745zi_q_stm32h745xx_m4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NUCLEO_H745ZI_Q_STM32H745XX_M4
vendor: st
