architecture: arm
board_socs:
- name: stm32f415xx
defconfig_file: boards/mikroe/mini_m4_for_stm32/mikroe_mini_m4_for_stm32_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MIKROE_MINI_M4_FOR_STM32
vendor: mikroe
