architecture: xtensa
board_socs:
- name: esp32s3
defconfig_file: boards/espressif/esp32s3_devkitm/esp32s3_devkitm_procpu_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ESP32S3_DEVKITM_ESP32S3_PROCPU
vendor: espressif
