architecture: arm
board_socs:
- name: efm32gg11b820f2048gl192
defconfig_file: boards/silabs/starter_kits/slstk3701a/slstk3701a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLSTK3701A
vendor: silabs
