architecture: arm
board_socs:
- name: efm32gg11b820f2048gl192
defconfig_file: boards/silabs/efm32gg_stk3701a/efm32gg_stk3701a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFM32GG_STK3701A
vendor: silabs
