architecture: xtensa
board_socs:
- name: esp32s3
defconfig_file: boards/heltec/heltec_wireless_stick_lite_v3/heltec_wireless_stick_lite_v3_esp32s3_procpu_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_HELTEC_WIRELESS_STICK_LITE_V3_ESP32S3_PROCPU
vendor: heltec
