architecture: arm
board_socs:
- name: cy8c6347
defconfig_file: boards/cypress/cy8ckit_062_ble/cy8ckit_062_ble_cy8c6347_m0_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_CY8CKIT_062_BLE_0_0_0_CY8C6347_M0
vendor: cypress
