architecture: arm64
board_socs:
- name: ls1046a
  variants:
  - name: smp
    variants:
    - name: 4cores
defconfig_file: boards/nxp/ls1046ardb/ls1046ardb_ls1046a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_LS1046ARDB
vendor: nxp
