architecture: arm64
board_socs:
- name: mimx8mn6
  variants:
  - cpucluster: a53
    name: smp
defconfig_file: boards/nxp/imx8mn_evk/imx8mn_evk_mimx8mn6_a53_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_IMX8MN_EVK_MIMX8MN6_A53
vendor: nxp
