architecture: arm
board_socs:
- name: efm32gg11b820f2048gm64
defconfig_file: boards/silabs/radio_boards/slwrb4321a/slwrb4321a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLWRB4321A
vendor: silabs
