architecture: arm
board_socs:
- name: efm32gg11b820f2048gm64
defconfig_file: boards/silabs/efm32gg_slwstk6121a/efm32gg_slwstk6121a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFM32GG_SLWSTK6121A
vendor: silabs
