architecture: arm
board_socs:
- name: mimxrt685s
defconfig_file: boards/nxp/mimxrt685_evk/mimxrt685_evk_mimxrt685s_cm33_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_MIMXRT685_EVK_MIMXRT685S_CM33
vendor: nxp
