architecture: arm
board_socs:
- name: efr32mg12p433f1024gm68
defconfig_file: boards/silabs/radio_boards/slwrb4170a/slwrb4170a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLWRB4170A
vendor: unknown
