architecture: arm
board_socs:
- name: mimxrt1176
defconfig_file: boards/nxp/vmu_rt1170/vmu_rt1170_mimxrt1176_cm7_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_VMU_RT1170_MIMXRT1176_CM7
vendor: nxp
