architecture: riscv
board_socs:
- name: riscv_virtual_renode
defconfig_file: boards/renode/riscv32_virtual/riscv32_virtual_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_RISCV32_VIRTUAL
vendor: renode
