architecture: arm
board_socs:
- name: mcimx6x
defconfig_file: boards/udoo/udoo_neo_full/udoo_neo_full_mcimx6x_m4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_UDOO_NEO_FULL_MCIMX6X_M4
vendor: udoo
