architecture: arm64
board_socs:
- name: mimx9596
  variants:
  - cpucluster: a55
    name: smp
  - cpucluster: m7
    name: ddr
defconfig_file: boards/nxp/imx95_evk/imx95_evk_mimx9596_a55_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_IMX95_EVK_MIMX9596_A55
vendor: nxp
