architecture: arm
board_socs:
- name: efr32bg27c140f768im40
defconfig_file: boards/silabs/dev_kits/xg27_dk2602a/xg27_dk2602a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_XG27_DK2602A
vendor: silabs
