architecture: arm
board_socs:
- name: efr32bg27c140f768im40
defconfig_file: boards/silabs/efr32_thunderboard/efr32bg27_brd2602a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFR32BG27_BRD2602A
vendor: silabs
