architecture: arm64
board_socs:
- name: am6234
defconfig_file: boards/phytec/phyboard_lyra/phyboard_lyra_am6234_a53_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_PHYBOARD_LYRA_AM6234_A53
vendor: phytec
