architecture: arm
board_socs:
- name: efm32hg322f64
defconfig_file: boards/silabs/efm32hg_slstk3400a/efm32hg_slstk3400a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFM32HG_SLSTK3400A
vendor: silabs
