architecture: arm64
board_socs:
- name: agilex
defconfig_file: boards/intel/socfpga/agilex_socdk/intel_socfpga_agilex_socdk_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_INTEL_SOCFPGA_AGILEX_SOCDK
vendor: unknown
