architecture: xtensa
board_socs:
- name: esp32
defconfig_file: boards/espressif/esp32_devkitc_wrover/esp32_devkitc_wrover_procpu_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ESP32_DEVKITC_WROVER_ESP32_PROCPU
vendor: espressif
