architecture: arm
board_socs:
- name: stm32f401xe
- name: nrf51822
defconfig_file: boards/96boards/carbon/96b_carbon_stm32f401xe_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_96B_CARBON_STM32F401XE
vendor: 96boards
