architecture: arm
board_socs:
- name: efm32gg12b810f1024gm64
defconfig_file: boards/silabs/efm32gg_sltb009a/efm32gg_sltb009a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFM32GG_SLTB009A
vendor: silabs
