architecture: arm64
board_socs:
- name: r8a779f0
defconfig_file: boards/renesas/rcar_spider_s4/rcar_spider_s4_r8a779f0_a55_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_RCAR_SPIDER_S4_R8A779F0_A55
vendor: renesas
