architecture: arm
board_socs:
- name: cyble_416045_02
defconfig_file: boards/cypress/cy8cproto_063_ble/cy8cproto_063_ble_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_CY8CPROTO_063_BLE
vendor: cypress
