architecture: arm
board_socs:
- name: nrf54l20
defconfig_file: boards/nordic/nrf54l20pdk/nrf54l20pdk_nrf54l20_cpuapp_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NRF54L20PDK_NRF54L20_CPUAPP
vendor: nordic
