architecture: riscv
board_socs:
- name: polarfire
defconfig_file: boards/beagle/beaglev_fire/beaglev_fire_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_BEAGLEV_FIRE
select:
- 64BIT
- SCHED_IPI_SUPPORTED
- CPU_HAS_FPU_DOUBLE_PRECISION
vendor: beagle
