architecture: arm64
board_socs:
- name: agilex5
defconfig_file: boards/intel/socfpga/agilex5_socdk/intel_socfpga_agilex5_socdk_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_INTEL_SOCFPGA_AGILEX5_SOCDK
vendor: unknown
