architecture: xtensa
board_socs:
- name: esp32s3
defconfig_file: boards/espressif/esp32s3_devkitc/esp32s3_devkitc_esp32s3_appcpu_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ESP32S3_DEVKITC_ESP32S3_APPCPU
vendor: espressif
