architecture: arm
board_socs:
- name: renesas_rzt2m
defconfig_file: boards/renesas/rzt2m_starterkit/rzt2m_starter_kit_renesas_rzt2m_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_RZT2M_STARTER_KIT
vendor: renesas
