architecture: arm
board_socs:
- name: stm32f401xe
- name: nrf51822
defconfig_file: boards/96boards/carbon/96b_carbon_nrf51822_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_96B_CARBON_NRF51822
vendor: 96boards
