architecture: xtensa
board_socs:
- name: esp32
defconfig_file: boards/heltec/heltec_wifi_lora32_v2/heltec_wifi_lora32_v2_procpu_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_HELTEC_WIFI_LORA32_V2_ESP32_PROCPU
vendor: heltec
