architecture: arm
board_socs:
- name: mcimx7d
defconfig_file: boards/96boards/meerkat96/96b_meerkat96_mcimx7d_m4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_96B_MEERKAT96_MCIMX7D_M4
vendor: 96boards
