architecture: arm
board_socs:
- name: efm32pg12b500f1024gl125
- name: efm32jg12b500f1024gl125
defconfig_file: boards/silabs/starter_kits/slstk3402a/slstk3402a_efm32jg12b500f1024gl125_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_SLSTK3402A_EFM32JG12B500F1024GL125
vendor: silabs
