architecture: arm
board_socs:
- name: efm32pg1b200f256gm48
defconfig_file: boards/silabs/efm32pg_stk3401a/efm32pg_stk3401a_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EFM32PG_STK3401A
vendor: silabs
