architecture: arm
board_socs:
- name: nrf9161
  variants:
  - name: ns
defconfig_file: boards/nordic/nrf9161dk/nrf9161dk_nrf9161_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_NRF9161DK_0_7_0_NRF9161
vendor: nordic
