architecture: arc
board_socs:
- name: emsdp_em4
- name: emsdp_em5d
- name: emsdp_em6
- name: emsdp_em7d
- name: emsdp_em7d_esp
- name: emsdp_em9d
- name: emsdp_em11d
defconfig_file: boards/snps/emsdp/emsdp_emsdp_em6_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_EMSDP_EMSDP_EM4
vendor: snps
