architecture: arm
board_socs:
- name: nrf52832
defconfig_file: boards/qorvo/decawave_dwm1001_dev/decawave_dwm1001_dev_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_DECAWAVE_DWM1001_DEV
vendor: qorvo
