architecture: xtensa
board_socs:
- name: mimx8ud7
defconfig_file: boards/nxp/imx8ulp_evk/imx8ulp_evk_mimx8ud7_adsp_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_IMX8ULP_EVK_IMX8ULP_ADSP
vendor: nxp
