architecture: arm
board_socs:
- name: cy8c6247
defconfig_file: boards/cypress/cy8ckit_062_wifi_bt/cy8ckit_062_wifi_bt_cy8c6247_m0_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_CY8CKIT_062_WIFI_BT_CY8C6247_M0
vendor: cypress
