architecture: xtensa
board_socs:
- name: esp32
defconfig_file: boards/espressif/esp32_devkitc_wroom/esp32_devkitc_wroom_esp32_appcpu_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_ESP32_DEVKITC_WROOM_ESP32_APPCPU
vendor: espressif
