architecture: arm
board_socs:
- name: lpc54114
defconfig_file: boards/nxp/lpcxpresso54114/lpcxpresso54114_lpc54114_m4_defconfig
remove_defconfig_flags:
- CONFIG_BOARD_LPCXPRESSO54114_LPC54114_M4
vendor: nxp
